version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'acdibble'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      prisma:
        patterns:
          - '*prisma*'
      trpc:
        patterns:
          - '@trpc*'
      types:
        patterns:
          - '@types/*'
