[project]
name = "python-client"
version = "0.1.0"
# description = "Add your description here"
# readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "aiohttp>=3.10.11",
    "cryptography>=46.0.3",
    "python-socketio>=5.16.0",
]
