name: Publish @chainflip-io/cli ğŸ›°ï¸

on:
  push:
    # tags:
    #   - "@chainflip-io/cli/*"

permissions:
  packages: write
  contents: read

env:
  NODE_AUTH_TOKEN: ${{ secrets.CF_NPM_JS_PACKAGES_READ_WRITE }}

jobs:
  publish-cli:
    uses: ./.github/workflows/_30_publish_npm.yml
    with:
      package_name: cli
    secrets: inherit
